#!/usr/bin/env python

from AutoADAG import *
import ConfigParser
from Pegasus.DAX3 import *
import getpass
import logging
import math
import optparse
import os
import re
import socket
import string
import subprocess
import sys
import time



# to setup python lib dir for importing Pegasus PYTHON DAX API
pegasus_config = os.path.join("pegasus-config") + " --noeoln --python"
lib_dir = subprocess.Popen(pegasus_config,
                           stdout=subprocess.PIPE,
                           shell=True).communicate()[0]
#Insert this directory in our search path
os.sys.path.insert(0, lib_dir)


# --- global variables ----------------------------------------------------------------

logger      = logging.getLogger("my_logger")
conf        = None
added_execs = []


# --- classes -------------------------------------------------------------------------

class ComputeJob(Job):
    """ A Pegasus DAX Job with extra information such as cpu and memory
    requirements, for both single and peagaus-mpi-cluster execution
    """

    def __init__(self, name, cores=1, mem_gb=2, partition="part1"):
        Job.__init__(self, name=name)
        
        # label based clustering
        self.addProfile(Profile(Namespace.PEGASUS, 
                                key="label",
                                value=partition))
  
        # required for the Pegasus accounting
        self.addProfile(Profile(Namespace.PEGASUS,
                                key="cores",
                                value=str(cores)))
  
        # standard resource requirements for all jobs
        mem_mb = mem_gb * 1000
        self.addProfile(Profile(Namespace.CONDOR,
                                key="request_cpus",
                                value=str(cores)))
        self.addProfile(Profile(Namespace.PEGASUS,
                                key="pmc_request_cpus",
                                value=str(cores)))
        self.addProfile(Profile(Namespace.CONDOR,
                                key="request_memory",
                                value=str(mem_mb)))
        self.addProfile(Profile(Namespace.PEGASUS,
                                key="pmc_request_memory",
                                value=str(mem_mb)))
        self.addProfile(Profile(Namespace.CONDOR,
                                key="request_disk",
                                value=str(20*1024*1024)))

        # special sauce for TACC - we want smaller jobs to go to the normal
        # compute nodes and the large memory ones to go to the large memory
        # nodes
        if re.search('stampede', conf.get("local", "exec_env")):
            hosts = conf.get("exec_environment", "hosts_" + partition)
            cores = str(16 * int(hosts))
            self.addProfile(Profile(Namespace.GLOBUS,
                                    key="queue",
                                    value="normal"))
            self.addProfile(Profile(Namespace.GLOBUS,
                                    key="hostcount",
                                    value=hosts))
            self.addProfile(Profile(Namespace.GLOBUS,
                                    key="count",
                                    value=cores))
            self.addProfile(Profile(Namespace.ENV,
                                    key="PMC_HOST_MEMORY",
                                    value="29000"))


# --- functions -----------------------------------------------------------------------


def setup_logger(verbose):
    """ Use a console logger for all output to the user """

    # log to the console
    console = logging.StreamHandler()

    # default log level - make logger/console match
    logger.setLevel(logging.INFO)
    console.setLevel(logging.INFO)

    if verbose:
        logger.setLevel(logging.DEBUG)
        console.setLevel(logging.DEBUG)

    # formatter
    formatter = logging.Formatter("%(asctime)s %(levelname)7s:  %(message)s")
    console.setFormatter(formatter)
    logger.addHandler(console)
    logger.debug("Logger has been configured")


def myexec(cmd_line):
    """ Convenience function as we are shelling out a fair amount """
    
    sys.stdout.flush()
    p = subprocess.Popen(cmd_line + " 2>&1", shell=True)
    stdoutdata, stderrdata = p.communicate()
    r = p.returncode
    if r != 0:
        raise RuntimeError("Command '%s' failed with error code %s" \
                           % (cmd_line, r))


def proxy_check():
    """ Verify that the user has a proxy and it is valid for a long time """
    p = subprocess.Popen("grid-proxy-info -timeleft", shell=True, 
                         stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    stdoutdata, stderrdata = p.communicate()
    r = p.returncode
    if r != 0:
        logger.error(stderrdata)
        raise RuntimeError("Command '%s' failed with error code %s" \
                           % (cmd_line, r))
    timeleft = int(stdoutdata)

    # two weeks minimum lifetime
    if timeleft < (60*60*24*10):
        raise RuntimeError("There is not enough time left on your grid" +
                           " proxy. Please renew, then run this command" +
                           " again")

        
def generate_site_catalog():
    """ Uses a templete file to produce the Pegasus site catalog """
    
    logger.info("Generating sites.catalog")
    inf = open("conf/" + conf.get("local", "exec_env") + 
               "/sites.catalog.template", 'r')
    template = string.Template(inf.read())
    inf.close()

    outf = open(conf.get("local", "work_dir") + "/sites.catalog", "w")
    outf.write(template.substitute(
                        submit_host = socket.gethostname(),
                        username = getpass.getuser(), 
                        home = os.path.expanduser('~'),
                        top_dir = conf.get("local", "top_dir"),
                        work_dir = conf.get("local", "work_dir"),
                        pegasus_bin = conf.get("local", "pegasus_bin"),
                        irods_bin = conf.get("local", "irods_bin"),
                        tacc_allocation = conf.get("tacc", "allocation"),
                        tacc_username = conf.get("tacc", "username"),
                        tacc_storage_group = conf.get("tacc", "storage_group"),
              ))
    outf.close()
#    inf = open(conf.get("local", "top_dir") + "/input-gvcfs.txt", "r")
#    for line in inf.readlines():
#        line = line.rstrip('\n')
#        line = line.rstrip('\r')
#        newline = line + ".idx"
#        fastq_urls.append(line)
#        fastq_urls.append(newline)
#    inf.close()
#
#    # sanity checks
#    if len(fastq_urls) == 0:
#        logger.error("Did not find fastq files")
#        sys.exit(1)
def read_input_lists(ref_urls, fastq_urls):
    """ The user provides a list of reference file URLs and pairs of fastq 
    URLs to be processed.
    """
    # first the reference
    inf = open(conf.get("local", "top_dir") + "/inputs-ref.txt", "r")
    for line in inf.readlines():
        line = line.rstrip('\n')
        ref_urls.append(line)
    inf.close()

    inf = open(conf.get("local", "top_dir") + "/input-gvcfs.txt", "r")
    index_files = []
    vcf_files  = []
    for line in inf.readlines():
        line = line.rstrip('\n')
        if line.endswith("vcf"):
            vcf_files.append(line)
        else:
            index_files.append(line)
    fastq_urls['vcf_files'] = vcf_files
    fastq_urls['index_files'] = index_files
    inf.close()

    # sanity checks
    if len(fastq_urls) == 0:
        logger.error("Did not find fastq files")
        sys.exit(1)
    if len(fastq_urls) % 2 != 0:
        logger.error("Found an uneven number of fastq files in input list")
        sys.exit(1)



def extract_lfn(url):
    """ determine a logical file name (basename) from a given URL """
    return re.sub(".*/", "", url)


def local_pfn(path):
    """ generates a full pfn given a local path """
    pfn = "scp://" + getpass.getuser() + "@" + socket.gethostname() + "/" + path
    return pfn
  

def extract_sample_name(url):
    """ sample name is the fist part of the base name (for example:
    HN0001 from HN001_FCD1P1JACXX_L6_SZAIPI024836-36_1.fq)
    """
    name = re.sub(".*/", "", url)
    name = re.sub("_.*", "", name)
    return name

def add_executable(dax, logical_name, wrapper_name):
    """ adds executables to the DAX-level replica catalog """
    global added_execs

    if logical_name in added_execs:
        return

    base_url = local_pfn(conf.get("local", "top_dir"))    
    
    wrapper = Executable(name=logical_name, 
                         arch="x86_64",
                         installed=False)
    wrapper.addPFN(PFN(base_url + "/wrappers/" + wrapper_name, "local"))
    dax.addExecutable(wrapper)

    added_execs.append(logical_name)

def extract_fasta_basefile(file_list):
    """ find the base fasta file given a list of reference files """
    for f in file_list:
        if re.search("(.fa|.fasta)$", f.name):
            return f


def combine_variants(dax, software_file, ref_files, wf_files):
    add_executable(dax, "combine_variants", "gatk-wrapper")
    j = ComputeJob("combine_variants", cores = 1, mem_gb = 10,
                   partition = "part3")
    
    j.uses(software_file, link=Link.INPUT)
    for f in ref_files:
        j.uses(f, link=Link.INPUT)
    for i in range(1, 21):
        fname = conf.get("local", "run_id") + "-" + "GVCF_Chr%02d.vcf" % (i)
        logger.info("  Added variant file for combine variants %s " %(wf_files[fname].name))
        j.uses(wf_files[fname], link=Link.INPUT)
        j.uses(wf_files[fname + ".idx"], link=Link.INPUT)
    
    fname = conf.get("local", "run_id") + "-" + "All.vcf"
    wf_files[fname] = File(fname)
    logger.info("  Added output for combine variants %s " %(wf_files[fname].name))
    j.uses(wf_files[fname], link=Link.OUTPUT, transfer=True)
    wf_files[fname + ".idx"] = File(fname + ".idx")
    j.uses(wf_files[fname + ".idx"], link=Link.OUTPUT, transfer=True)
    
    j.addArguments("-T", "CombineVariants",
            "-R", extract_fasta_basefile(ref_files),
            "-o", wf_files[fname])
    for i in range(1, 21):
        fname = conf.get("local", "run_id") + "-" + "GVCF_Chr%02d.vcf" % (i)
        j.addArguments("--variant", wf_files[fname])
    dax.addJob(j)
    
    # filter the results    
    wf_files[conf.get("local", "run_id") + "-" + 'All_filtered_snp.vcf'] = \
            File(conf.get("local", "run_id") + "-" + "All_filtered_snp.vcf")
    wf_files[conf.get("local", "run_id") + "-" + 'All_filtered_snp.vcf.idx'] = \
            File(conf.get("local", "run_id") + "-" + "All_filtered_snp.vcf.idx")
    select_and_filter_snp(dax, software_file, ref_files, wf_files,
                          wf_files[conf.get("local", "run_id") + "-" + 'All.vcf'],
                          wf_files[conf.get("local", "run_id") + "-" + 'All_filtered_snp.vcf'],
                          wf_files[conf.get("local", "run_id") + "-" + 'All_filtered_snp.vcf.idx'])
    
    wf_files[conf.get("local", "run_id") + "-" + 'All_filtered_indel.vcf'] = \
            File(conf.get("local", "run_id") + "-" + "All_filtered_indel.vcf")
    wf_files[conf.get("local", "run_id") + "-" + 'All_filtered_indel.vcf.idx'] = \
            File(conf.get("local", "run_id") + "-" + "All_filtered_indel.vcf.idx")
    select_and_filter_indel(dax, software_file, ref_files, wf_files,
                            wf_files[conf.get("local", "run_id") + "-" + 'All.vcf'],
                            wf_files[conf.get("local", "run_id") + "-" + 'All_filtered_indel.vcf'],
                            wf_files[conf.get("local", "run_id") + "-" + 'All_filtered_indel.vcf.idx'])
    
    
def genotype_gvcfs(dax, software_file, ref_files, wf_files,chromosome):

    add_executable(dax, "genotype_gvcfs", "gatk-wrapper")
    j = ComputeJob("genotype_gvcfs", cores = 1, mem_gb = 10,
                   partition = "part2")
    
    # inputs
    
    j.uses(software_file, link=Link.INPUT)
    for f in ref_files:
        j.uses(f, link=Link.INPUT)
    fname = conf.get("local", "run_id") + "-" + "combinegvcf" + chromosome + ".vcf"
    f = wf_files[fname]
    j.uses(f, link=Link.INPUT)
    j.uses(wf_files[fname + ".idx"], link=Link.INPUT)
    
    

    # outputs
    fname = conf.get("local", "run_id") + "-" + "GVCF_" + chromosome + ".vcf"
    wf_files[fname] = File(fname)
    j.uses(wf_files[fname], link=Link.OUTPUT, transfer=False)
    wf_files[fname + ".idx"] = File(fname + ".idx")
    j.uses(wf_files[fname + ".idx"], link=Link.OUTPUT, transfer=False)
    
    j.addArguments("-T", "GenotypeGVCFs",
                   "-R", extract_fasta_basefile(ref_files),
                   "-o", wf_files[fname],"-L", chromosome,"-V",f)
    dax.addJob(j)
    
def combine_gvcfs(sample_name, dax, software_file, ref_files, wf_files,vcf_files,index_files,chromosome):

    add_executable(dax, "combine_gvcfs", "gatk-wrapper")
    j = ComputeJob("combine_gvcfs", cores = 1, mem_gb = 20,
                   partition = "part2")
    
    # inputs
    j.uses(software_file, link=Link.INPUT)
    for f in ref_files:
        j.uses(f, link=Link.INPUT)
    
    for f in vcf_files:
        j.uses(f, link=Link.INPUT)
        j.addArguments("--variant",f)
    for f in index_files:
        j.uses(f, link=Link.INPUT)
    
    
    # outputs
    fname = conf.get("local", "run_id") + "-" + "combinegvcf" + chromosome + ".vcf"
    wf_files[fname] = File(fname)
    j.uses(wf_files[fname], link=Link.OUTPUT, transfer=False)
    wf_files[fname + ".idx"] = File(fname + ".idx")
    j.uses(wf_files[fname + ".idx"], link=Link.OUTPUT, transfer=False)
    
    j.addArguments("-T", "CombineGVCFs",
                   "-R", extract_fasta_basefile(ref_files),"-o", wf_files[fname],
                   "-L",chromosome)
    dax.addJob(j)
    return j


def select_and_filter_snp(dax, software_file, ref_files, wf_files,
                          in_file, out_file, out_idx):
    
    # we need an intermediate file
    intername = re.sub(".*/", "", in_file.name) + "_snp_only.vcf"
    wf_files[intername] = File(intername) 
    
    add_executable(dax, "select_variants_snp", "gatk-wrapper")    
    j = ComputeJob("select_variants_snp", cores = 14, mem_gb = 10,
                   partition = "part3")
    
    # inputs
    j.uses(software_file, link=Link.INPUT)
    for f in ref_files:
        j.uses(f, link=Link.INPUT)
    j.uses(in_file, link=Link.INPUT)

    # outputs
    j.uses(wf_files[intername], link=Link.OUTPUT, transfer=False)
    
    j.addArguments("-T", "SelectVariants",
                   "-nt", "15",
                   "-R", extract_fasta_basefile(ref_files),
                   "-selectType", "SNP",
                   "-V", in_file,
                   "-o", wf_files[intername])
    
    dax.addJob(j)

    add_executable(dax, "filtering_snp", "gatk-wrapper")    
    j = ComputeJob("filtering_snp", cores = 1, mem_gb = 10,
                   partition = "part3")
    
    # inputs
    j.uses(software_file, link=Link.INPUT)
    for f in ref_files:
        j.uses(f, link=Link.INPUT)
    j.uses(wf_files[intername], link=Link.INPUT)

    # outputs
    j.uses(out_file, link=Link.OUTPUT, transfer=True)
    j.uses(out_idx, link=Link.OUTPUT, transfer=True)
    
    j.addArguments("-T", "VariantFiltration",
                   "-R", extract_fasta_basefile(ref_files),
                   "-V", wf_files[intername],
                   "--filterExpression", "'QD < 2.0 || FS > 60.0 || MQ < 40.0  || Haplotypescore > 20.0'",
                   "--filterName", "my_snp_filter",
                   "-o", out_file)

    dax.addJob(j)
    
def select_and_filter_indel(dax, software_file, ref_files, wf_files,
                            in_file, out_file, out_idx):

    # we need an intermediate file
    intername = re.sub(".*/", "", in_file.name) + "_indel_only.vcf"
    wf_files[intername] = File(intername) 

        
    add_executable(dax, "select_variants_indel", "gatk-wrapper")    
    j = ComputeJob("select_variants_indel", cores = 14, mem_gb = 10,
                   partition = "part3")
    
    # inputs
    j.uses(software_file, link=Link.INPUT)
    for f in ref_files:
        j.uses(f, link=Link.INPUT)
    j.uses(in_file, link=Link.INPUT)

    # outputs
    j.uses(wf_files[intername], link=Link.OUTPUT, transfer=False)
    
    j.addArguments("-T", "SelectVariants",
                   "-nt", "15",
                   "-R", extract_fasta_basefile(ref_files),
                   "-selectType", "INDEL",
                   "-V", in_file,
                   "-o", wf_files[intername])
 
    dax.addJob(j)
 
    add_executable(dax, "filtering_indel", "gatk-wrapper")    
    j = ComputeJob("filtering_indel", cores = 1, mem_gb = 10,
                   partition = "part3")
    
    # inputs
    j.uses(software_file, link=Link.INPUT)
    for f in ref_files:
        j.uses(f, link=Link.INPUT)
    j.uses(wf_files[intername], link=Link.INPUT)

    # outputs
    j.uses(out_file, link=Link.OUTPUT, transfer=True)
    j.uses(out_idx, link=Link.OUTPUT, transfer=True)
    
    j.addArguments("-T", "VariantFiltration",
                   "-R", extract_fasta_basefile(ref_files),
                   "-V", wf_files[intername],
                   "--filterExpression", "'QD < 2.0 || FS > 200.0 || MQ < 40 || Haplotypescore > 20.0'",
                   "--filterName", "my_indel_filter",
                   "-o", out_file)
 
    dax.addJob(j)   
    
def generate_dax():
    """ generates the Pegasus DAX (directed acyclic graph - abstract XML)
    which is a description of a workflow """
    
    logger.info("Generating abstract workflow (DAX)")
    
    dax = AutoADAG("downstream_vcf_analysis")
    
    # The key to adding jobs to this workflow is the AutoADAG - it allows you
    # to add jobs with listed input and output files, and then the AutoADAG
    # will figure out the relationships between the jobs. There is no need
    # to list parent/child relationships, but you can do that if you feel it
    # makes the relationships more clear than just specifying the
    # inputs/outputs.
        
    # email notificiations for when the state of the workflow changes
    dax.invoke('all',  conf.get("local", "pegasus_bin") +
                       "/../share/pegasus/notification/email")
    
    ref_urls = []
    fastq_urls = {}
    read_input_lists(ref_urls,fastq_urls)
    # determine how many TACC compute nodes we need
    num_inputs_in_set = min(len(fastq_urls) / 2, 100)
    conf.set("exec_environment", "hosts_part1", str( (num_inputs_in_set // 16 + 1) * 4 ))
    conf.set("exec_environment", "hosts_part2", str( (num_inputs_in_set // 16 + 1) * 4 ))
    conf.set("exec_environment", "hosts_part3", str( 1 ))

    # we need to bring a copy of the software with us
    software_tar = File("software.tar.gz")
    software_tar.addPFN(PFN(local_pfn(conf.get("local", "work_dir") + "/software.tar.gz"), "local"))
    dax.addFile(software_tar)    
    add_executable(dax, "software-wrapper", "software-wrapper")
    software_job = ComputeJob("software-wrapper", cores=1, mem_gb=1)
    software_job.uses(software_tar, link=Link.INPUT)
    dax.addJob(software_job)

    # we need to track files across jobs
    wf_files = {}
    sample_names = []
    ref_files = []
    vcf_files = []
    index_files =  []
    for url in ref_urls:
        f = File(extract_lfn(url))
        f.addPFN(PFN(url, "irods_iplant"))
        dax.addFile(f)
        # put these in a list so jobs can pick them up
        ref_files.append(f)
    print fastq_urls['vcf_files']
    for vcf in fastq_urls['vcf_files']:
        # input files for this lane   
        f = File(extract_lfn(vcf))
        f.addPFN(PFN(vcf, "irods_iplant"))
        dax.addFile(f)
        sample_name = extract_sample_name(f.name)
        logger.info("  Added variant file %s " %(f.name))
        vcf_files.append(f)
    print fastq_urls['index_files']
    for idxfile in fastq_urls['index_files']:        
        f = File(extract_lfn(idxfile))
        f.addPFN(PFN(idxfile, "irods_iplant"))
        dax.addFile(f)
        logger.info("  Added index file %s" %(f.name))
        index_files.append(f)
    # handle the different line endings
    
    for i in range(1, 21):
        chromosome = "Chr%02d" %(i)
        combine_job = combine_gvcfs(sample_name, dax, software_tar, ref_files, wf_files,vcf_files,index_files,chromosome)
        dax.depends(parent=software_job,child=combine_job)
        genotype_gvcfs(dax, software_tar, ref_files, wf_files,chromosome)
    combine_variants(dax,software_tar, ref_files, wf_files)
    dax_file = open(conf.get("local", "work_dir") + "/dowstr.dax", "w")
    dax.writeXML(dax_file)
    dax_file.close()


def main():
    global conf
    
    setup_logger(False)

    # Configure command line option parser
    prog_usage = "usage: workflow-generator [options]"
    parser = optparse.OptionParser(usage=prog_usage)

    parser.add_option("-e", "--exec-env", action = "store", dest = "exec_env",
                      help = "Handle for the target execution environment.")

    # Parse command line options
    (options, args) = parser.parse_args()
    if options.exec_env == None:
        logger.fatal("Please specify an execution environment with --exec-env")
        sys.exit(1)

    # read the config file and add those settings to the option object
    conf = ConfigParser.SafeConfigParser({'username': getpass.getuser()})
    r = conf.read([os.environ['HOME'] + "/.soybean-workflow.conf", \
                  "conf/%s/site.conf" % options.exec_env])
    if len(r) != 2:
        logger.fatal("Unable to read configuration files for that environment")
        sys.exit(1)

    conf.set("local", "username", getpass.getuser())
    conf.set("local", "exec_env", options.exec_env)
    conf.set("local", "top_dir", os.path.dirname(os.path.realpath( __file__ )))

    # run id
    conf.set("local", "run_id", time.strftime("%Y%m%d-%H%M%S", time.gmtime()))

    # add the run id to the work dir
    conf.set("local", "work_dir", conf.get("local", "work_dir") + "/" + 
                                  conf.get("local", "run_id"))
    
    # local Pegasus environment
    pegasus_config = os.path.join("pegasus-config") + " --noeoln --bin"
    pegasus_bin_dir = subprocess.Popen(pegasus_config,
                                       stdout=subprocess.PIPE,
                                       shell=True).communicate()[0]
    conf.set("local", "pegasus_bin", pegasus_bin_dir)

    # check proxy before doing anything else
    proxy_check()
    
    # create a local work directory for the workflow
    logger.info("Setting up work directory at %s" \
                %(conf.get("local", "work_dir")))
    if os.path.exists(conf.get("local", "work_dir")):
        logger.fatal("Work directory already exists") 
        os.exit(1)
    os.makedirs(conf.get("local", "work_dir"))

    # tar up the software
    logger.info("Tarring up software directory to send with jobs")
    myexec("tar czf " + conf.get("local", "work_dir") + \
           "/software.tar.gz software")

    generate_site_catalog()

    # FIXME: what should we copy / keep in the top dir?
    myexec("cp conf/" + conf.get("local", "exec_env") + 
           "/transformations.catalog " + 
           conf.get("local", "work_dir") + "/transformations.catalog")
    myexec("cp conf/" + conf.get("local", "exec_env") + 
           "/replica.catalog " + 
           conf.get("local", "work_dir") + "/replica.catalog")

    generate_dax()

    # submit
    logger.info("Planning workflow...")
    os.chdir(conf.get("local", "work_dir"))
    cmd = "pegasus-plan" + \
          " --conf " + conf.get("local", "top_dir") + \
          "/conf/" + conf.get("local", "exec_env") + "/pegasus.conf" + \
          " --dir ." + \
          " --relative-dir wf-" + conf.get("local", "run_id") + \
          " --sites execution"
    
    if conf.get("exec_environment", "output_site") != "":
        cmd += " --output-site " + conf.get("exec_environment", "output_site")
              
    if conf.get("exec_environment", "staging_site") != "":
        cmd += " --staging " + conf.get("exec_environment", "staging_site")
          
    if conf.get("exec_environment", "job_clustering") != "":
        cmd += " --cluster " + conf.get("exec_environment", "job_clustering")
          
    cmd += " --dax dowstr.dax"
    logger.info(cmd)
    myexec(cmd + " 2>&1 | tee pegasus-plan.out")


if __name__ == "__main__":
    main()